services:
  api:
    build: .
    container_name: ai-blog-api
    command: bun run start
    env_file:
      - .env
    ports:
      - "8080:8080"

  worker:
    build: .
    container_name: ai-blog-worker
    command: bun run start:worker
    env_file:
      - .env

  mongo:
    image: mongo:8

  redis:
    image: redis:7-alpine
